In [1]:
# This printed folder is the base for any relative path
import os
print(os.getcwd())

/Users/nandipha/Desktop/masters/notebooks

from pathlib import Path

csv_path = Path("folder1") / "folder2" / "folder3" / "file_name.csv"
print("Resolved path:", csv_path.resolve())
print("Exists?", csv_path.exists())

In [4]:
from pathlib import Path

file_path = Path("results") / "all_results.csv"
print("Resolved path:", file_path.resolve())
print("Exists?", file_path.exists())

Resolved path: /Users/nandipha/Desktop/masters/notebooks/results/all_results.csv
Exists? False

In [41]:
from pathlib import Path
import pandas as pd

file_path = Path("..") / "results" / "all_results.csv"
print("Resolved:", file_path.resolve())
print("Exists?:", file_path.exists())

df = pd.read_csv(file_path)
df.head()

Resolved: /Users/nandipha/Desktop/masters/results/all_results.csv
Exists?: True

,run_key,run_id,run_timestamp,case_study,tier,model_name,window_length_L,feature_mode,uses_time_features,contiguity_enforced,score_definition,threshold_strategy,threshold_value,val_event_precision,val_event_recall,val_event_f1,val_event_delay_median_minutes,test_event_precision,test_event_recall,test_event_f1,test_event_delay_median_minutes,test_point_precision,test_point_recall,test_point_f1,test_auroc,test_pr_auc,train_seconds,score_seconds,notes
0,case=aiops_kpi|tier=0|model=heuristic_static_z...,20260115_134541,2026-01-15T13:45:41.872608,aiops_kpi,0,heuristic_static_z_abs_value_scaled,0,none,0,1,abs(value_scaled) at each timestamp,val_event_f1,1.236076e+01,1.0000,0.636364,0.777778,3.0,1.000000,0.026316,0.051282,3.0,1.000000,0.000285,0.000571,0.990738,0.986497,0.000000,0.212661,conservative_threshold_test;conservative_thres...
1,case=aiops_kpi|tier=0|model=heuristic_moving_z...,20260115_135221,2026-01-15T13:52:21.203347,aiops_kpi,0,heuristic_moving_z_60min_abs_value_scaled,0,none,0,1,abs((value_scaled - moving_mean_60min) / movin...,val_event_f1,7.015874e+00,0.4375,0.636364,0.518519,1.0,1.000000,0.368421,0.538462,1.0,1.000000,0.004853,0.009659,0.113286,0.135861,0.000000,1.015743,threshold=val_event_f1
2,case=aiops_kpi|tier=0|model=heuristic_moving_m...,20260115_145933,2026-01-15T14:59:33.694121,aiops_kpi,0,heuristic_moving_median_mad_60min_abs_value_sc...,0,none,0,1,abs((value_scaled - moving_median_60min) / max...,val_event_f1,4.971024e+06,1.0000,0.272727,0.428571,1.0,1.000000,0.105263,0.190476,4.5,1.000000,0.003711,0.007395,0.219297,0.155849,0.000000,2.286121,conservative_threshold_val;threshold=val_event_f1
3,case=aiops_kpi|tier=0|model=heuristic_moving_m...,20260115_152426,2026-01-15T15:24:26.321147,aiops_kpi,0,heuristic_moving_median_mad_floor_60min_abs_va...,0,none,0,1,abs((value_scaled - moving_median_60min) / max...,val_event_f1,5.366124e+01,1.0000,0.363636,0.533333,2.0,1.000000,0.026316,0.051282,4.0,1.000000,0.000143,0.000285,0.217925,0.184899,0.000000,2.492912,conservative_threshold_test;conservative_thres...
4,case=aiops_kpi|tier=1|model=isolation_forest_w...,20260115_193640,2026-01-15T19:36:40.508549,aiops_kpi,1,isolation_forest_window_features,60,summary,1,1,IsolationForest score = -decision_function(win...,val_event_f1,1.318871e-01,0.9000,1.000000,0.947368,2.0,0.676056,0.973684,0.798023,3.0,0.390054,0.071653,0.121066,0.952413,0.621024,6.252302,1.505661,threshold=val_event_f1

In [42]:
df.to_excel("exports/all_results_full.xlsx", index=False)

ModuleNotFoundError: No module named 'openpyxl'

In [32]:
import pandas as pd

pd.set_option("display.max_columns", None)   # show all columns
pd.set_option("display.width", None)         # don't wrap based on terminal width

df.head()

,run_key,run_id,run_timestamp,case_study,tier,model_name,window_length_L,feature_mode,uses_time_features,contiguity_enforced,score_definition,threshold_strategy,threshold_value,val_event_precision,val_event_recall,val_event_f1,val_event_delay_median_minutes,test_event_precision,test_event_recall,test_event_f1,test_event_delay_median_minutes,test_point_precision,test_point_recall,test_point_f1,test_auroc,test_pr_auc,train_seconds,score_seconds,notes
0,case=aiops_kpi|tier=0|model=heuristic_static_z...,20260115_102100,2026-01-15T10:21:00.973746,aiops_kpi,0,heuristic_static_z_abs_value_scaled,0,none,0,1,abs(value_scaled) at each timestamp,val_event_f1,12.360756,1.0000,0.636364,0.777778,3.0,1.0,0.026316,0.051282,3.0,1.0,0.000285,0.000571,0.990738,0.986497,0.0,0.106837,high_pr_auc_low_event_recall_mismatch;val_to_t...
1,case=aiops_kpi|tier=0|model=heuristic_moving_z...,20260115_094427,2026-01-15T09:44:27.734960,aiops_kpi,0,heuristic_moving_z_60min_abs_value_scaled,0,none,0,1,abs((value_scaled - moving_mean_60min) / movin...,val_event_f1,7.015874,0.4375,0.636364,0.518519,1.0,1.0,0.368421,0.538462,1.0,1.0,0.004853,0.009659,0.113286,0.135861,0.0,0.772620,thr=val_event_f1;model=heuristic_moving_z_60mi...

In [7]:
from pathlib import Path
import pandas as pd

csv_path = (
    Path("..")
    / "results"
    / "aiops_kpi"
    / "baselines_event"
    / "runs"
    / "20260113_001453_aiops_kpi_heuristic_static_z_abs_value_scaled"
    / "aiops_kpi_static_z_test_metrics.csv"   # <-- change this filename if your csv is named differently
)

print("Resolved:", csv_path.resolve())
print("Exists?:", csv_path.exists())

df = pd.read_csv(csv_path)
df.head()

Resolved: /Users/nandipha/Desktop/masters/results/aiops_kpi/baselines_event/runs/20260113_001453_aiops_kpi_heuristic_static_z_abs_value_scaled/aiops_kpi_static_z_test_metrics.csv
Exists?: True

,split,event_precision,event_recall,event_f1,event_delay_median_minutes,point_precision,point_recall,point_f1,auroc,pr_auc
0,test,1.0,0.026316,0.051282,3.0,1.0,0.000285,0.000571,0.990738,0.986497

In [32]:
len(df)

7267

In [33]:
!jupyter nbconvert --to pdf "notebooks/SEE.ipynb"

zsh:1: command not found: jupyter

In [34]:
from pathlib import Path
Path("notebooks/SEE.ipynb").exists()

True

In [36]:
import sys
!{sys.executable} -m pip install "nbconvert[webpdf]"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbconvert[webpdf] in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (7.16.6)
Requirement already satisfied: beautifulsoup4 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from bleach[css]!=5.0.0->nbconvert[webpdf]) (6.2.0)
Requirement already satisfied: defusedxml in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (0.7.1)
Requirement already satisfied: importlib-metadata>=3.6 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (8.7.0)
Requirement already satisfied: jinja2>=3.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (3.1.6)
Requirement already satisfied: jupyter-core>=4.7 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (5.8.1)
Requirement already satisfied: jupyterlab-pygments in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (3.1.4)
Requirement already satisfied: nbclient>=0.5.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (5.10.4)
Requirement already satisfied: packaging in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (25.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (2.19.2)
Requirement already satisfied: traitlets>=5.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (5.14.3)
Collecting playwright (from nbconvert[webpdf])
  Downloading playwright-1.57.0-py3-none-macosx_11_0_universal2.whl.metadata (3.5 kB)
Requirement already satisfied: typing-extensions in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from mistune<4,>=2.0.3->nbconvert[webpdf]) (4.15.0)
Requirement already satisfied: webencodings in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert[webpdf]) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from bleach[css]!=5.0.0->nbconvert[webpdf]) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=3.6->nbconvert[webpdf]) (3.23.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-core>=4.7->nbconvert[webpdf]) (4.4.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbclient>=0.5.0->nbconvert[webpdf]) (8.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (2.9.0.post0)
Requirement already satisfied: pyzmq>=23.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (27.1.0)
Requirement already satisfied: tornado>=6.2 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (6.5.2)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbformat>=5.7->nbconvert[webpdf]) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbformat>=5.7->nbconvert[webpdf]) (4.25.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (0.27.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (1.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4->nbconvert[webpdf]) (2.8)
Collecting pyee<14,>=13 (from playwright->nbconvert[webpdf])
  Downloading pyee-13.0.0-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright->nbconvert[webpdf])
  Downloading greenlet-3.2.4-cp39-cp39-macosx_11_0_universal2.whl.metadata (4.1 kB)
Downloading playwright-1.57.0-py3-none-macosx_11_0_universal2.whl (42.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 MB 2.8 MB/s  0:00:15m0:00:0100:01
Downloading greenlet-3.2.4-cp39-cp39-macosx_11_0_universal2.whl (269 kB)
Downloading pyee-13.0.0-py3-none-any.whl (15 kB)
Installing collected packages: pyee, greenlet, playwright
   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [playwright]  WARNING: The script playwright is installed in '/Users/nandipha/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [playwright]
Successfully installed greenlet-3.2.4 playwright-1.57.0 pyee-13.0.0

In [38]:
import sys
!{sys.executable} -m playwright install chromium

You are using a frozen ffmpeg browser which does not receive updates anymore on mac12. Please update to the latest version of your operating system to test up-to-date browsers.

In [39]:
import sys
!{sys.executable} -m playwright install chromium --dry-run

browser: chromium version 143.0.7499.4
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/chromium-1200
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1200/chromium-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/chromium/1200/chromium-mac.zip

browser: ffmpeg
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/ffmpeg_mac12_special-1010
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/ffmpeg/1010/ffmpeg-mac.zip

browser: chromium-headless-shell version 143.0.7499.4
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/chromium_headless_shell-1200
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-headless-shell-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1200/chromium-headless-shell-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/chromium/1200/chromium-headless-shell-mac.zip

browser: ffmpeg
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/ffmpeg_mac12_special-1010
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/ffmpeg/1010/ffmpeg-mac.zip

In [40]:
import sys
!{sys.executable} -m playwright install chromium

You are using a frozen ffmpeg browser which does not receive updates anymore on mac12. Please update to the latest version of your operating system to test up-to-date browsers.

In [41]:
from pathlib import Path

cache_dir = Path.home() / "Library" / "Caches" / "ms-playwright"
print("Cache dir:", cache_dir)
print("Exists?:", cache_dir.exists())

if cache_dir.exists():
    items = sorted([p.name for p in cache_dir.iterdir()])
    print("Top-level items:", items[:30])

Cache dir: /Users/nandipha/Library/Caches/ms-playwright
Exists?: True
Top-level items: ['.links', 'chromium-1200', 'chromium_headless_shell-1200', 'ffmpeg_mac12_special-1010']

In [45]:
import sys
!mkdir -p exports
!{sys.executable} -m nbconvert --to webpdf --allow-chromium-download "notebooks/SEE.ipynb" --output-dir "exports"

[NbConvertApp] Converting notebook notebooks/SEE.ipynb to webpdf
[NbConvertApp] Building PDF
You are using a frozen ffmpeg browser which does not receive updates anymore on mac12. Please update to the latest version of your operating system to test up-to-date browsers.
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 150894 bytes to exports/SEE.pdf