In [27]:
# This printed folder is the base for any relative path
import os
print(os.getcwd())

/Users/nandipha/Desktop/masters

from pathlib import Path

csv_path = Path("folder1") / "folder2" / "folder3" / "file_name.csv"
print("Resolved path:", csv_path.resolve())
print("Exists?", csv_path.exists())

In [46]:
from pathlib import Path

file_path = Path("results") / "all_results.csv"
print("Resolved path:", file_path.resolve())
print("Exists?", file_path.exists())

Resolved path: /Users/nandipha/Desktop/masters/results/all_results.csv
Exists? True

In [47]:
import pandas as pd
df = pd.read_csv(file_path)
df.head()

,run_id,case_study,model_name,window_length_L,threshold_strategy,chosen_threshold,validation_precision,validation_recall,validation_f1_score,validation_window_count,...,test_true_positives,test_false_positives,test_false_negatives,test_window_count,score_definition,if_n_estimators,if_random_state,ocsvm_kernel,ocsvm_gamma,ocsvm_nu
0,20260106_165601,aiops_kpi,tier0_static_window_end_rule,360,Validation F1 maximisation,2.4887,1.0000,0.6456,0.7846,NaN,...,189,0,6716,44926,value_scaled at window end,NaN,NaN,NaN,NaN,NaN
1,20260106_165601,aiops_kpi,isolation_forest,360,Validation F1 maximisation,0.6751,0.4928,0.4304,0.4595,NaN,...,89,255,6816,44926,NaN,200.0,42.0,NaN,NaN,NaN
2,20260106_165601,aiops_kpi,ocsvm_rbf,360,Validation F1 maximisation,167.8293,0.0308,0.4051,0.0573,15473.0,...,6522,2455,383,44926,NaN,NaN,NaN,rbf,scale,0.1

In [48]:
df.tail()

,run_id,case_study,model_name,window_length_L,threshold_strategy,chosen_threshold,validation_precision,validation_recall,validation_f1_score,validation_window_count,...,test_true_positives,test_false_positives,test_false_negatives,test_window_count,score_definition,if_n_estimators,if_random_state,ocsvm_kernel,ocsvm_gamma,ocsvm_nu
0,20260106_165601,aiops_kpi,tier0_static_window_end_rule,360,Validation F1 maximisation,2.4887,1.0000,0.6456,0.7846,NaN,...,189,0,6716,44926,value_scaled at window end,NaN,NaN,NaN,NaN,NaN
1,20260106_165601,aiops_kpi,isolation_forest,360,Validation F1 maximisation,0.6751,0.4928,0.4304,0.4595,NaN,...,89,255,6816,44926,NaN,200.0,42.0,NaN,NaN,NaN
2,20260106_165601,aiops_kpi,ocsvm_rbf,360,Validation F1 maximisation,167.8293,0.0308,0.4051,0.0573,15473.0,...,6522,2455,383,44926,NaN,NaN,NaN,rbf,scale,0.1

In [32]:
len(df)

7267

In [33]:
!jupyter nbconvert --to pdf "notebooks/SEE.ipynb"

zsh:1: command not found: jupyter

In [34]:
from pathlib import Path
Path("notebooks/SEE.ipynb").exists()

True

In [36]:
import sys
!{sys.executable} -m pip install "nbconvert[webpdf]"

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: nbconvert[webpdf] in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (7.16.6)
Requirement already satisfied: beautifulsoup4 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (4.14.3)
Requirement already satisfied: bleach!=5.0.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from bleach[css]!=5.0.0->nbconvert[webpdf]) (6.2.0)
Requirement already satisfied: defusedxml in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (0.7.1)
Requirement already satisfied: importlib-metadata>=3.6 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (8.7.0)
Requirement already satisfied: jinja2>=3.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (3.1.6)
Requirement already satisfied: jupyter-core>=4.7 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (5.8.1)
Requirement already satisfied: jupyterlab-pygments in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (3.1.4)
Requirement already satisfied: nbclient>=0.5.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (0.10.2)
Requirement already satisfied: nbformat>=5.7 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (5.10.4)
Requirement already satisfied: packaging in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (25.0)
Requirement already satisfied: pandocfilters>=1.4.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (1.5.1)
Requirement already satisfied: pygments>=2.4.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (2.19.2)
Requirement already satisfied: traitlets>=5.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbconvert[webpdf]) (5.14.3)
Collecting playwright (from nbconvert[webpdf])
  Downloading playwright-1.57.0-py3-none-macosx_11_0_universal2.whl.metadata (3.5 kB)
Requirement already satisfied: typing-extensions in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from mistune<4,>=2.0.3->nbconvert[webpdf]) (4.15.0)
Requirement already satisfied: webencodings in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert[webpdf]) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from bleach[css]!=5.0.0->nbconvert[webpdf]) (1.4.0)
Requirement already satisfied: zipp>=3.20 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from importlib-metadata>=3.6->nbconvert[webpdf]) (3.23.0)
Requirement already satisfied: platformdirs>=2.5 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-core>=4.7->nbconvert[webpdf]) (4.4.0)
Requirement already satisfied: jupyter-client>=6.1.12 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbclient>=0.5.0->nbconvert[webpdf]) (8.6.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (2.9.0.post0)
Requirement already satisfied: pyzmq>=23.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (27.1.0)
Requirement already satisfied: tornado>=6.2 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (6.5.2)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbformat>=5.7->nbconvert[webpdf]) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from nbformat>=5.7->nbconvert[webpdf]) (4.25.1)
Requirement already satisfied: attrs>=22.2.0 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from jsonschema>=2.6->nbformat>=5.7->nbconvert[webpdf]) (0.27.1)
Requirement already satisfied: six>=1.5 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from python-dateutil>=2.8.2->jupyter-client>=6.1.12->nbclient>=0.5.0->nbconvert[webpdf]) (1.15.0)
Requirement already satisfied: soupsieve>=1.6.1 in /Users/nandipha/Library/Python/3.9/lib/python/site-packages (from beautifulsoup4->nbconvert[webpdf]) (2.8)
Collecting pyee<14,>=13 (from playwright->nbconvert[webpdf])
  Downloading pyee-13.0.0-py3-none-any.whl.metadata (2.9 kB)
Collecting greenlet<4.0.0,>=3.1.1 (from playwright->nbconvert[webpdf])
  Downloading greenlet-3.2.4-cp39-cp39-macosx_11_0_universal2.whl.metadata (4.1 kB)
Downloading playwright-1.57.0-py3-none-macosx_11_0_universal2.whl (42.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 MB 2.8 MB/s  0:00:15m0:00:0100:01
Downloading greenlet-3.2.4-cp39-cp39-macosx_11_0_universal2.whl (269 kB)
Downloading pyee-13.0.0-py3-none-any.whl (15 kB)
Installing collected packages: pyee, greenlet, playwright
   ━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━ 2/3 [playwright]  WARNING: The script playwright is installed in '/Users/nandipha/Library/Python/3.9/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [playwright]
Successfully installed greenlet-3.2.4 playwright-1.57.0 pyee-13.0.0

In [38]:
import sys
!{sys.executable} -m playwright install chromium

You are using a frozen ffmpeg browser which does not receive updates anymore on mac12. Please update to the latest version of your operating system to test up-to-date browsers.

In [39]:
import sys
!{sys.executable} -m playwright install chromium --dry-run

browser: chromium version 143.0.7499.4
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/chromium-1200
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1200/chromium-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/chromium/1200/chromium-mac.zip

browser: ffmpeg
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/ffmpeg_mac12_special-1010
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/ffmpeg/1010/ffmpeg-mac.zip

browser: chromium-headless-shell version 143.0.7499.4
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/chromium_headless_shell-1200
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/chromium/1200/chromium-headless-shell-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/chromium/1200/chromium-headless-shell-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/chromium/1200/chromium-headless-shell-mac.zip

browser: ffmpeg
  Install location:    /Users/nandipha/Library/Caches/ms-playwright/ffmpeg_mac12_special-1010
  Download url:        https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 1: https://playwright.download.prss.microsoft.com/dbazure/download/playwright/builds/ffmpeg/1010/ffmpeg-mac.zip
  Download fallback 2: https://cdn.playwright.dev/builds/ffmpeg/1010/ffmpeg-mac.zip

In [40]:
import sys
!{sys.executable} -m playwright install chromium

You are using a frozen ffmpeg browser which does not receive updates anymore on mac12. Please update to the latest version of your operating system to test up-to-date browsers.

In [41]:
from pathlib import Path

cache_dir = Path.home() / "Library" / "Caches" / "ms-playwright"
print("Cache dir:", cache_dir)
print("Exists?:", cache_dir.exists())

if cache_dir.exists():
    items = sorted([p.name for p in cache_dir.iterdir()])
    print("Top-level items:", items[:30])

Cache dir: /Users/nandipha/Library/Caches/ms-playwright
Exists?: True
Top-level items: ['.links', 'chromium-1200', 'chromium_headless_shell-1200', 'ffmpeg_mac12_special-1010']

In [45]:
import sys
!mkdir -p exports
!{sys.executable} -m nbconvert --to webpdf --allow-chromium-download "notebooks/SEE.ipynb" --output-dir "exports"

[NbConvertApp] Converting notebook notebooks/SEE.ipynb to webpdf
[NbConvertApp] Building PDF
You are using a frozen ffmpeg browser which does not receive updates anymore on mac12. Please update to the latest version of your operating system to test up-to-date browsers.
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 150894 bytes to exports/SEE.pdf